export const Countries = [
  {code: 'AF', unicode: 'U+1F1E6 U+1F1EB', name: 'Afghanistan', emoji: '🇦🇫', nameAr: 'أفغانستان'},
  {code: 'AL', unicode: 'U+1F1E6 U+1F1F1', name: 'Albania', emoji: '🇦🇱', nameAr: 'ألبانيا'},
  {code: 'DZ', unicode: 'U+1F1E9 U+1F1FF', name: 'Algeria', emoji: '🇩🇿', nameAr: 'الجزائر '},
  {code: 'AD', unicode: 'U+1F1E6 U+1F1E9', name: 'Andorra', emoji: '🇦🇩', nameAr: ' أندورا '},
  {code: 'AO', unicode: 'U+1F1E6 U+1F1F4', name: 'Angola', emoji: '🇦🇴', nameAr: ' أنغولا'},
  {code: 'AI', unicode: 'U+1F1E6 U+1F1EE', name: 'Anguilla', emoji: '🇦🇮', nameAr: 'أنغويلا '},
  {code: 'AQ', unicode: 'U+1F1E6 U+1F1F6', name: 'Antarctica', emoji: '🇦🇶', nameAr: 'أنتاركتيكا'},
  {code: 'AR', unicode: 'U+1F1E6 U+1F1F7', name: 'Argentina', emoji: '🇦🇷', nameAr: 'الأرجنتين '},
  {code: 'AM', unicode: 'U+1F1E6 U+1F1F2', name: 'Armenia', emoji: '🇦🇲', nameAr: ' أرمينيا'},
  {code: 'AW', unicode: 'U+1F1E6 U+1F1FC', name: 'Aruba', emoji: '🇦🇼', nameAr: 'أروبا'},
  {code: 'AU', unicode: 'U+1F1E6 U+1F1FA', name: 'Australia', emoji: '🇦🇺', nameAr: 'أستراليا'},
  {code: 'AT', unicode: 'U+1F1E6 U+1F1F9', name: 'Austria', emoji: '🇦🇹', nameAr: ' النمسا'},
  {code: 'AZ', unicode: 'U+1F1E6 U+1F1FF', name: 'Azerbaijan', emoji: '🇦🇿', nameAr: ' أذربيجان'},
  {code: 'BS', unicode: 'U+1F1E7 U+1F1F8', name: 'Bahamas', emoji: '🇧🇸', nameAr: 'الباهاماس'},
  {code: 'BH', unicode: 'U+1F1E7 U+1F1ED', name: 'Bahrain', emoji: '🇧🇭', nameAr: ' البحرين'},
  {code: 'BD', unicode: 'U+1F1E7 U+1F1E9', name: 'Bangladesh', emoji: '🇧🇩', nameAr: ' بنغلاديش'},
  {code: 'BB', unicode: 'U+1F1E7 U+1F1E7', name: 'Barbados', emoji: '🇧🇧', nameAr: ' بربادوس'},
  {code: 'BY', unicode: 'U+1F1E7 U+1F1FE', name: 'Belarus', emoji: '🇧🇾', nameAr: ' روسيا البيضاء'},
  {code: 'BE', unicode: 'U+1F1E7 U+1F1EA', name: 'Belgium', emoji: '🇧🇪', nameAr: ' بلجيكا'},
  {code: 'BZ', unicode: 'U+1F1E7 U+1F1FF', name: 'Belize', emoji: '🇧🇿', nameAr: ' بيليز'},
  {code: 'BJ', unicode: 'U+1F1E7 U+1F1EF', name: 'Benin', emoji: '🇧🇯', nameAr: 'بنين'},
  {code: 'BM', unicode: 'U+1F1E7 U+1F1F2', name: 'Bermuda', emoji: '🇧🇲', nameAr: ' جزر برمود'},
  {code: 'BT', unicode: 'U+1F1E7 U+1F1F9', name: 'Bhutan', emoji: '🇧🇹', nameAr: ' بوتان'},
  {code: 'BO', unicode: 'U+1F1E7 U+1F1F4', name: 'Bolivia', emoji: '🇧🇴', nameAr: ' بوليفيا'},
  {code: 'BW', unicode: 'U+1F1E7 U+1F1FC', name: 'Botswana', emoji: '🇧🇼', nameAr: ' بوتسوانا'},
  {code: 'BR', unicode: 'U+1F1E7 U+1F1F7', name: 'Brazil', emoji: '🇧🇷', nameAr: ' البرازيل'},
  {code: 'BN', unicode: 'U+1F1E7 U+1F1F3', name: 'Brunei', emoji: '🇧🇳', nameAr: ' بروناي'},
  {code: 'BG', unicode: 'U+1F1E7 U+1F1EC', name: 'Bulgaria', emoji: '🇧🇬', nameAr: ' بلغاريا'},
  {code: 'BF', unicode: 'U+1F1E7 U+1F1EB', name: 'Burkina Faso', emoji: '🇧🇫', nameAr: ' بوركينا فاسو'},
  {code: 'BI', unicode: 'U+1F1E7 U+1F1EE', name: 'Burundi', emoji: '🇧🇮', nameAr: ' بوروندي'},
  {code: 'KH', unicode: 'U+1F1F0 U+1F1ED', name: 'Cambodia', emoji: '🇰🇭', nameAr: ' كمبوديا'},
  {code: 'CM', unicode: 'U+1F1E8 U+1F1F2', name: 'Cameroon', emoji: '🇨🇲', nameAr: 'كاميرون'},
  {code: 'CA', unicode: 'U+1F1E8 U+1F1E6', name: 'Canada', emoji: '🇨🇦', nameAr: ' كندا'},
  {code: 'CV', unicode: 'U+1F1E8 U+1F1FB', name: 'Cape Verde', emoji: '🇨🇻', nameAr: 'الرأس الأخضر'},
  {code: 'KY', unicode: 'U+1F1F0 U+1F1FE', name: 'Cayman Islands', emoji: '🇰🇾', nameAr: ''},
  {code: 'TD', unicode: 'U+1F1F9 U+1F1E9', name: 'Chad', emoji: '🇹🇩', nameAr: 'تشاد'},
  {code: 'CL', unicode: 'U+1F1E8 U+1F1F1', name: 'Chile', emoji: '🇨🇱', nameAr: 'تشيلي'},
  {code: 'CN', unicode: 'U+1F1E8 U+1F1F3', name: 'China', emoji: '🇨🇳', nameAr: ' جمهورية الصين الشعبية'},
  {code: 'CX', unicode: 'U+1F1E8 U+1F1FD', name: 'Christmas Island', emoji: '🇨🇽', nameAr: ' '},
  {code: 'CC', unicode: 'U+1F1E8 U+1F1E8', name: 'Cocos (Keeling) Islands', emoji: '🇨🇨', nameAr: ' '},
  {code: 'CO', unicode: 'U+1F1E8 U+1F1F4', name: 'Colombia', emoji: '🇨🇴', nameAr: ' كولومبيا'},
  {code: 'KM', unicode: 'U+1F1F0 U+1F1F2', name: 'Comoros', emoji: '🇰🇲', nameAr: 'جزر القمر'},
  {code: 'CK', unicode: 'U+1F1E8 U+1F1F0', name: 'Cook Islands', emoji: '🇨🇰', nameAr: 'جزر كوك'},
  {code: 'CR', unicode: 'U+1F1E8 U+1F1F7', name: 'Costa Rica', emoji: '🇨🇷', nameAr: 'كوستاريكا'},
  {code: 'HR', unicode: 'U+1F1ED U+1F1F7', name: 'Croatia', emoji: '🇭🇷', nameAr: 'كرواتيا'},
  {code: 'CU', unicode: 'U+1F1E8 U+1F1FA', name: 'Cuba', emoji: '🇨🇺', nameAr: 'كوبا'},
  {code: 'CY', unicode: 'U+1F1E8 U+1F1FE', name: 'Cyprus', emoji: '🇨🇾', nameAr: ' قبرص'},
  {code: 'DK', unicode: 'U+1F1E9 U+1F1F0', name: 'Denmark', emoji: '🇩🇰', nameAr: ' الدانمارك'},
  {code: 'DJ', unicode: 'U+1F1E9 U+1F1EF', name: 'Djibouti', emoji: '🇩🇯', nameAr: ' جيبوتي'},
  {code: 'DM', unicode: 'U+1F1E9 U+1F1F2', name: 'Dominica', emoji: '🇩🇲', nameAr: ' دومينيكا'},
  {code: 'DO', unicode: 'U+1F1E9 U+1F1F4', name: 'Dominican Republic', emoji: '🇩🇴', nameAr: 'الجمهورية الدومينيكية'},
  {code: 'EC', unicode: 'U+1F1EA U+1F1E8', name: 'Ecuador', emoji: '🇪🇨', nameAr: ' إكوادور'},
  {code: 'EG', unicode: 'U+1F1EA U+1F1EC', name: 'Egypt', emoji: '🇪🇬', nameAr: ' مصر'},
  {code: 'SV', unicode: 'U+1F1F8 U+1F1FB', name: 'El Salvador', emoji: '🇸🇻', nameAr: ' إلسلفادور'},
  {code: 'GQ', unicode: 'U+1F1EC U+1F1F6', name: 'Equatorial Guinea', emoji: '🇬🇶', nameAr: 'غينيا الاستوائي'},
  {code: 'ER', unicode: 'U+1F1EA U+1F1F7', name: 'Eritrea', emoji: '🇪🇷', nameAr: 'إريتريا'},
  {code: 'EE', unicode: 'U+1F1EA U+1F1EA', name: 'Estonia', emoji: '🇪🇪', nameAr: ' استونيا'},
  {code: 'ET', unicode: 'U+1F1EA U+1F1F9', name: 'Ethiopia', emoji: '🇪🇹', nameAr: 'أثيوبيا'},
  {code: 'FK', unicode: 'U+1F1EB U+1F1F0', name: 'Falkland Islands', emoji: '🇫🇰', nameAr: 'جزر فوكلاند'},
  {code: 'FO', unicode: 'U+1F1EB U+1F1F4', name: 'Faroe Islands', emoji: '🇫🇴', nameAr: 'جزر فارو'},
  {code: 'FJ', unicode: 'U+1F1EB U+1F1EF', name: 'Fiji', emoji: '🇫🇯', nameAr: 'فيجي'},
  {code: 'FI', unicode: 'U+1F1EB U+1F1EE', name: 'Finland', emoji: '🇫🇮', nameAr: 'فنلندا'},
  {code: 'FR', unicode: 'U+1F1EB U+1F1F7', name: 'France', emoji: '🇫🇷', nameAr: 'فرنسا'},
  {code: 'GF', unicode: 'U+1F1EC U+1F1EB', name: 'French Guiana', emoji: '🇬🇫', nameAr: 'غويانا الفرنسية'},
  {code: 'PF', unicode: 'U+1F1F5 U+1F1EB', name: 'French Polynesia', emoji: '🇵🇫', nameAr: 'بولينيزيا الفرنسية'},
  {code: 'GA', unicode: 'U+1F1EC U+1F1E6', name: 'Gabon', emoji: '🇬🇦', nameAr: ' الغابون'},
  {code: 'GM', unicode: 'U+1F1EC U+1F1F2', name: 'Gambia', emoji: '🇬🇲', nameAr: ' غامبيا'},
  {code: 'GE', unicode: 'U+1F1EC U+1F1EA', name: 'Georgia', emoji: '🇬🇪', nameAr: ' جيورجيا'},
  {code: 'DE', unicode: 'U+1F1E9 U+1F1EA', name: 'Germany', emoji: '🇩🇪', nameAr: ' ألمانيا'},
  {code: 'GH', unicode: 'U+1F1EC U+1F1ED', name: 'Ghana', emoji: '🇬🇭', nameAr: ' غانا'},
  {code: 'GR', unicode: 'U+1F1EC U+1F1F7', name: 'Greece', emoji: '🇬🇷', nameAr: ' اليونان'},
  {code: 'GL', unicode: 'U+1F1EC U+1F1F1', name: 'Greenland', emoji: '🇬🇱', nameAr: ' جرينلاند'},
  {code: 'GD', unicode: 'U+1F1EC U+1F1E9', name: 'Grenada', emoji: '🇬🇩', nameAr: ' غرينادا'},
  {code: 'GP', unicode: 'U+1F1EC U+1F1F5', name: 'Guadeloupe', emoji: '🇬🇵', nameAr: ' جزر جوادلوب'},
  {code: 'GU', unicode: 'U+1F1EC U+1F1FA', name: 'Guam', emoji: '🇬🇺', nameAr: ' جوام'},
  {code: 'GT', unicode: 'U+1F1EC U+1F1F9', name: 'Guatemala', emoji: '🇬🇹', nameAr: ' غواتيمال'},
  {code: 'GN', unicode: 'U+1F1EC U+1F1F3', name: 'Guinea', emoji: '🇬🇳', nameAr: ' غينيا'},
  {code: 'GW', unicode: 'U+1F1EC U+1F1FC', name: 'Guinea-Bissau', emoji: '🇬🇼', nameAr: ' غينيا-بيساو'},
  {code: 'GY', unicode: 'U+1F1EC U+1F1FE', name: 'Guyana', emoji: '🇬🇾', nameAr: ' غيانا'},
  {code: 'HT', unicode: 'U+1F1ED U+1F1F9', name: 'Haiti', emoji: '🇭🇹', nameAr: ' هايتي '},
  {code: 'HN', unicode: 'U+1F1ED U+1F1F3', name: 'Honduras', emoji: '🇭🇳', nameAr: ' هندوراس '},
  {code: 'HU', unicode: 'U+1F1ED U+1F1FA', name: 'Hungary', emoji: '🇭🇺', nameAr: ' المجر '},
  {code: 'IS', unicode: 'U+1F1EE U+1F1F8', name: 'Iceland', emoji: '🇮🇸', nameAr: 'آيسلندا '},
  {code: 'IN', unicode: 'U+1F1EE U+1F1F3', name: 'India', emoji: '🇮🇳', nameAr: ' الهند '},
  {code: 'ID', unicode: 'U+1F1EE U+1F1E9', name: 'Indonesia', emoji: '🇮🇩', nameAr: ' أندونيسيا '},
  {code: 'IQ', unicode: 'U+1F1EE U+1F1F6', name: 'Iraq', emoji: '🇮🇶', nameAr: ' العراق '},
  {code: 'IL', unicode: 'U+1F1EE U+1F1F1', name: 'Israel', emoji: '🇮🇱', nameAr: ' إسرائيل '},
  {code: 'IT', unicode: 'U+1F1EE U+1F1F9', name: 'Italy', emoji: '🇮🇹', nameAr: ' إيطاليا '},
  {code: 'JM', unicode: 'U+1F1EF U+1F1F2', name: 'Jamaica', emoji: '🇯🇲', nameAr: ' جمايكا '},
  {code: 'JP', unicode: 'U+1F1EF U+1F1F5', name: 'Japan', emoji: '🇯🇵', nameAr: ' اليابان '},
  {code: 'JO', unicode: 'U+1F1EF U+1F1F4', name: 'Jordan', emoji: '🇯🇴', nameAr: ' الأردن '},
  {code: 'KZ', unicode: 'U+1F1F0 U+1F1FF', name: 'Kazakhstan', emoji: '🇰🇿', nameAr: ' كازاخستان '},
  {code: 'KE', unicode: 'U+1F1F0 U+1F1EA', name: 'Kenya', emoji: '🇰🇪', nameAr: ' كينيا '},
  {code: 'KI', unicode: 'U+1F1F0 U+1F1EE', name: 'Kiribati', emoji: '🇰🇮', nameAr: ' كيريباتي '},
  {code: 'KW', unicode: 'U+1F1F0 U+1F1FC', name: 'Kuwait', emoji: '🇰🇼', nameAr: ' الكويت '},
  {code: 'KG', unicode: 'U+1F1F0 U+1F1EC', name: 'Kyrgyzstan', emoji: '🇰🇬', nameAr: ' قيرغيزستان '},
  {code: 'LV', unicode: 'U+1F1F1 U+1F1FB', name: 'Latvia', emoji: '🇱🇻', nameAr: ' لاتفيا '},
  {code: 'LB', unicode: 'U+1F1F1 U+1F1E7', name: 'Lebanon', emoji: '🇱🇧', nameAr: ' لبنان '},
  {code: 'LS', unicode: 'U+1F1F1 U+1F1F8', name: 'Lesotho', emoji: '🇱🇸', nameAr: ' ليسوتو '},
  {code: 'LR', unicode: 'U+1F1F1 U+1F1F7', name: 'Liberia', emoji: '🇱🇷', nameAr: ' ليبيريا '},
  {code: 'LY', unicode: 'U+1F1F1 U+1F1FE', name: 'Libya', emoji: '🇱🇾', nameAr: ' ليبيا '},
  {code: 'LI', unicode: 'U+1F1F1 U+1F1EE', name: 'Liechtenstein', emoji: '🇱🇮', nameAr: ' ليختنشتين '},
  {code: 'LT', unicode: 'U+1F1F1 U+1F1F9', name: 'Lithuania', emoji: '🇱🇹', nameAr: ' لتوانيا '},
  {code: 'LU', unicode: 'U+1F1F1 U+1F1FA', name: 'Luxembourg', emoji: '🇱🇺', nameAr: ' لوكسمبورغ '},
  {code: 'MG', unicode: 'U+1F1F2 U+1F1EC', name: 'Madagascar', emoji: '🇲🇬', nameAr: ' مدغشقر '},
  {code: 'MW', unicode: 'U+1F1F2 U+1F1FC', name: 'Malawi', emoji: '🇲🇼', nameAr: ' مالاوي '},
  {code: 'MY', unicode: 'U+1F1F2 U+1F1FE', name: 'Malaysia', emoji: '🇲🇾', nameAr: ' ماليزيا '},
  {code: 'MV', unicode: 'U+1F1F2 U+1F1FB', name: 'Maldives', emoji: '🇲🇻', nameAr: ' المالديف '},
  {code: 'ML', unicode: 'U+1F1F2 U+1F1F1', name: 'Mali', emoji: '🇲🇱', nameAr: ' مالي '},
  {code: 'MT', unicode: 'U+1F1F2 U+1F1F9', name: 'Malta', emoji: '🇲🇹', nameAr: ' مالطا '},
  {code: 'MQ', unicode: 'U+1F1F2 U+1F1F6', name: 'Martinique', emoji: '🇲🇶', nameAr: ' مارتينيك '},
  {code: 'MR', unicode: 'U+1F1F2 U+1F1F7', name: 'Mauritania', emoji: '🇲🇷', nameAr: '  موريتانيا '},
  {code: 'MU', unicode: 'U+1F1F2 U+1F1FA', name: 'Mauritius', emoji: '🇲🇺', nameAr: ' موريشيوس '},
  {code: 'YT', unicode: 'U+1F1FE U+1F1F9', name: 'Mayotte', emoji: '🇾🇹', nameAr: ' '},
  {code: 'MX', unicode: 'U+1F1F2 U+1F1FD', name: 'Mexico', emoji: '🇲🇽', nameAr: ' المكسيك '},
  {code: 'MC', unicode: 'U+1F1F2 U+1F1E8', name: 'Monaco', emoji: '🇲🇨', nameAr: ' موناكو '},
  {code: 'MN', unicode: 'U+1F1F2 U+1F1F3', name: 'Mongolia', emoji: '🇲🇳', nameAr: ' منغوليا '},
  {code: 'ME', unicode: 'U+1F1F2 U+1F1EA', name: 'Montenegro', emoji: '🇲🇪', nameAr: 'الجبل الأسو'},
  {code: 'MS', unicode: 'U+1F1F2 U+1F1F8', name: 'Montserrat', emoji: '🇲🇸', nameAr: '  مونتسيرات '},
  {code: 'MA', unicode: 'U+1F1F2 U+1F1E6', name: 'Morocco', emoji: '🇲🇦', nameAr: ' المغرب '},
  {code: 'MZ', unicode: 'U+1F1F2 U+1F1FF', name: 'Mozambique', emoji: '🇲🇿', nameAr: ' موزمبيق '},
  {code: 'NA', unicode: 'U+1F1F3 U+1F1E6', name: 'Namibia', emoji: '🇳🇦', nameAr: ' ناميبيا '},
  {code: 'NR', unicode: 'U+1F1F3 U+1F1F7', name: 'Nauru', emoji: '🇳🇷', nameAr: ' ناورو '},
  {code: 'NP', unicode: 'U+1F1F3 U+1F1F5', name: 'Nepal', emoji: '🇳🇵', nameAr: ' نيبال '},
  {code: 'NL', unicode: 'U+1F1F3 U+1F1F1', name: 'Netherlands', emoji: '🇳🇱', nameAr: ' هولندا '},
  {code: 'NC', unicode: 'U+1F1F3 U+1F1E8', name: 'New Caledonia', emoji: '🇳🇨', nameAr: 'كاليدونيا الجديدة '},
  {code: 'NZ', unicode: 'U+1F1F3 U+1F1FF', name: 'New Zealand', emoji: '🇳🇿', nameAr: 'نيوزيلندا '},
  {code: 'NI', unicode: 'U+1F1F3 U+1F1EE', name: 'Nicaragua', emoji: '🇳🇮', nameAr: ' نيكاراجوا '},
  {code: 'NE', unicode: 'U+1F1F3 U+1F1EA', name: 'Niger', emoji: '🇳🇪', nameAr: ' النيجر '},
  {code: 'NG', unicode: 'U+1F1F3 U+1F1EC', name: 'Nigeria', emoji: '🇳🇬', nameAr: ' نيجيريا '},
  {code: 'NU', unicode: 'U+1F1F3 U+1F1FA', name: 'Niue', emoji: '🇳🇺', nameAr: ' نييوي '},
  {code: 'MP', unicode: 'U+1F1F2 U+1F1F5', name: 'Northern Mariana Islands', emoji: '🇲🇵', nameAr: 'جزر ماريانا الشمالية '},
  {code: 'NO', unicode: 'U+1F1F3 U+1F1F4', name: 'Norway', emoji: '🇳🇴', nameAr: ' النرويج '},
  {code: 'OM', unicode: 'U+1F1F4 U+1F1F2', name: 'Oman', emoji: '🇴🇲', nameAr: 'عُمان '},
  {code: 'PK', unicode: 'U+1F1F5 U+1F1F0', name: 'Pakistan', emoji: '🇵🇰', nameAr: ' باكستان '},
  {code: 'PW', unicode: 'U+1F1F5 U+1F1FC', name: 'Palau', emoji: '🇵🇼', nameAr: 'بالاو '},
  {code: 'PA', unicode: 'U+1F1F5 U+1F1E6', name: 'Panama', emoji: '🇵🇦', nameAr: ' بنما '},
  {code: 'PY', unicode: 'U+1F1F5 U+1F1FE', name: 'Paraguay', emoji: '🇵🇾', nameAr: ' باراغواي '},
  {code: 'PE', unicode: 'U+1F1F5 U+1F1EA', name: 'Peru', emoji: '🇵🇪', nameAr: ' بيرو '},
  {code: 'PH', unicode: 'U+1F1F5 U+1F1ED', name: 'Philippines', emoji: '🇵🇭', nameAr: 'الفليبين '},
  {code: 'PL', unicode: 'U+1F1F5 U+1F1F1', name: 'Poland', emoji: '🇵🇱', nameAr: ' بولندا '},
  {code: 'PT', unicode: 'U+1F1F5 U+1F1F9', name: 'Portugal', emoji: '🇵🇹', nameAr: ' البرتغال '},
  {code: 'QA', unicode: 'U+1F1F6 U+1F1E6', name: 'Qatar', emoji: '🇶🇦', nameAr: ' قطر '},
  {code: 'RO', unicode: 'U+1F1F7 U+1F1F4', name: 'Romania', emoji: '🇷🇴', nameAr: ' رومانيا '},
  {code: 'RW', unicode: 'U+1F1F7 U+1F1FC', name: 'Rwanda', emoji: '🇷🇼', nameAr: ' رواندا '},
  {code: 'WS', unicode: 'U+1F1FC U+1F1F8', name: 'Samoa', emoji: '🇼🇸', nameAr: 'ساموا'},
  {code: 'SM', unicode: 'U+1F1F8 U+1F1F2', name: 'San Marino', emoji: '🇸🇲', nameAr: 'سان مارينو '},
  {code: 'SA', unicode: 'U+1F1F8 U+1F1E6', name: 'Saudi Arabia', emoji: '🇸🇦', nameAr: 'المملكة العربية السعودية '},
  {code: 'SN', unicode: 'U+1F1F8 U+1F1F3', name: 'Senegal', emoji: '🇸🇳', nameAr: ' السنغال '},
  {code: 'RS', unicode: 'U+1F1F7 U+1F1F8', name: 'Serbia', emoji: '🇷🇸', nameAr: 'جمهورية صربيا'},
  {code: 'SC', unicode: 'U+1F1F8 U+1F1E8', name: 'Seychelles', emoji: '🇸🇨', nameAr: 'سيشيل '},
  {code: 'SL', unicode: 'U+1F1F8 U+1F1F1', name: 'Sierra Leone', emoji: '🇸🇱', nameAr: 'سيراليون '},
  {code: 'SG', unicode: 'U+1F1F8 U+1F1EC', name: 'Singapore', emoji: '🇸🇬', nameAr: ' سنغافورة '},
  {code: 'SI', unicode: 'U+1F1F8 U+1F1EE', name: 'Slovenia', emoji: '🇸🇮', nameAr: ' سلوفينيا '},
  {code: 'SO', unicode: 'U+1F1F8 U+1F1F4', name: 'Somalia', emoji: '🇸🇴', nameAr: ' الصومال '},
  {code: 'SS', unicode: 'U+1F1F8 U+1F1F8', name: 'South Sudan', emoji: '🇸🇸', nameAr: 'جنوب السودان'},
  {code: 'ES', unicode: 'U+1F1EA U+1F1F8', name: 'Spain', emoji: '🇪🇸', nameAr: ' إسبانيا '},
  {code: 'SD', unicode: 'U+1F1F8 U+1F1E9', name: 'Sudan', emoji: '🇸🇩', nameAr: ' السودان '},
  {code: 'SR', unicode: 'U+1F1F8 U+1F1F7', name: 'Suriname', emoji: '🇸🇷', nameAr: ' سورينام '},
  {code: 'SZ', unicode: 'U+1F1F8 U+1F1FF', name: 'Swaziland', emoji: '🇸🇿', nameAr: ' سوازيلند '},
  {code: 'SE', unicode: 'U+1F1F8 U+1F1EA', name: 'Sweden', emoji: '🇸🇪', nameAr: ' السويد '},
  {code: 'CH', unicode: 'U+1F1E8 U+1F1ED', name: 'Switzerland', emoji: '🇨🇭', nameAr: 'سويسرا '},
  {code: 'TJ', unicode: 'U+1F1F9 U+1F1EF', name: 'Tajikistan', emoji: '🇹🇯', nameAr: ' طاجيكستان '},
  {code: 'TZ', unicode: 'U+1F1F9 U+1F1FF', name: 'Tanzania', emoji: '🇹🇿', nameAr: ' تنزانيا '},
  {code: 'TH', unicode: 'U+1F1F9 U+1F1ED', name: 'Thailand', emoji: '🇹🇭', nameAr: ' تايلندا '},
  {code: 'TG', unicode: 'U+1F1F9 U+1F1EC', name: 'Togo', emoji: '🇹🇬', nameAr: ' توغو '},
  {code: 'TK', unicode: 'U+1F1F9 U+1F1F0', name: 'Tokelau', emoji: '🇹🇰', nameAr: '  '},
  {code: 'TO', unicode: 'U+1F1F9 U+1F1F4', name: 'Tonga', emoji: '🇹🇴', nameAr: ' تونغا '},
  {code: 'TN', unicode: 'U+1F1F9 U+1F1F3', name: 'Tunisia', emoji: '🇹🇳', nameAr: ' تونس '},
  {code: 'TR', unicode: 'U+1F1F9 U+1F1F7', name: 'Turkey', emoji: '🇹🇷', nameAr: ' تركيا '},
  {code: 'TM', unicode: 'U+1F1F9 U+1F1F2', name: 'Turkmenistan', emoji: '🇹🇲', nameAr: ' تركمانستان '},
  {code: 'TV', unicode: 'U+1F1F9 U+1F1FB', name: 'Tuvalu', emoji: '🇹🇻', nameAr: ' توفالو '},
  {code: 'UG', unicode: 'U+1F1FA U+1F1EC', name: 'Uganda', emoji: '🇺🇬', nameAr: ' أوغندا '},
  {code: 'UA', unicode: 'U+1F1FA U+1F1E6', name: 'Ukraine', emoji: '🇺🇦', nameAr: ' أوكرانيا '},
  {code: 'UY', unicode: 'U+1F1FA U+1F1FE', name: 'Uruguay', emoji: '🇺🇾', nameAr: '  أورغواي '},
  {code: 'UZ', unicode: 'U+1F1FA U+1F1FF', name: 'Uzbekistan', emoji: '🇺🇿', nameAr: '  أوزباكستان '},
  {code: 'VU', unicode: 'U+1F1FB U+1F1FA', name: 'Vanuatu', emoji: '🇻🇺', nameAr: ' فانواتو '},
  {code: 'VE', unicode: 'U+1F1FB U+1F1EA', name: 'Venezuela', emoji: '🇻🇪', nameAr: 'فنزويلا '},
  {code: 'VN', unicode: 'U+1F1FB U+1F1F3', name: 'Vietnam', emoji: '🇻🇳', nameAr: ' فيتنام '},
  {code: 'EH', unicode: 'U+1F1EA U+1F1ED', name: 'Western Sahara', emoji: '🇪🇭', nameAr: 'الصحراء الغربية '},
  {code: 'YE', unicode: 'U+1F1FE U+1F1EA', name: 'Yemen', emoji: '🇾🇪', nameAr: ' اليمن '},
  {code: 'ZM', unicode: 'U+1F1FF U+1F1F2', name: 'Zambia', emoji: '🇿🇲', nameAr: ' زامبيا '},
  {code: 'ZW', unicode: 'U+1F1FF U+1F1FC', name: 'Zimbabwe', emoji: '🇿🇼', nameAr: ' زمبابوي '},
];
